version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - echo Installing Gatsby-CLI...
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - echo Installing Node packages...
      - npm install
  build:
    commands:
      - echo Build initiated...
      - gatsby build
  post_build:
    commands:
      - echo Synchronizing public directory...
      - pwd
      - ls -lash $PWD/static
      - ls -lash
      - aws s3 sync ./public/ s3://mikebell.io --delete
artifacts:
  base-directory: public
  files:
    - '**/*'
  discard-paths: yes