baseURL: 'https://mikebell.io'
title: Mike Bell - Blog & Stuff
paginate: 5
theme: PaperMod
languageCode: en-gb

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: /about/
          weight: 1
        - name: Now
          url: /now/
          weight: 1
        - name: Search
          url: /search/
          weight: 2
        - name: CV
          url: /cv/
          weight: 3
        - name: Blog Roll
          url: /blog/roll/
          weight: 4
        - name: Archives
          url: /archives/
          weight: 5
        - name: Contact
          url: /contact/
          weight: 11

params:
  title: Mike Bell - Blog & Stuff
  description: 'My ramblings on engineering, homelabs and me/cfs.'
  author: Mike Bell

  # images: "/code.png"

  ShowReadingTime: true
  ShowShareButtons: false
  ShowFullTextinRSS: true
  comments: false
  defaultTheme: auto
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
    favicon: '/code.png'

  label:
    text: "Home"
    icon: /code.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Mike Bell - Blog & Stuff"
    Content:

  socialIcons:
    - name: mastodon
      url: 'https://remotelab.uk/@mikebell'
    - name: github
      url: 'https://github.com/mikebell'
    - name: email
      url: 'hello@mikebell.io'
    - name: rss
      url: 'https://mikebell.io/index.xml'

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: nord
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true

services:
  rss:
    limit: 10
