; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[entity][version] = "1.0"

projects[geshifilter][version] = "1.1"

projects[google_fonts][version] = "2.3"

projects[google_analytics][version] = "1.3"

projects[libraries][version] = "2.0"

projects[markdown][version] = "1.1"

projects[mollom][version] = "2.6"

projects[pathauto][version] = "1.2"

projects[rules][version] = "2.3"

projects[token][version] = "1.4"

projects[views][version] = "3.7"

projects[xmlsitemap][version] = "2.0-rc2"

projects[varnish][version] = "1.0-beta1"

projects[admin_menu][version] = "3.0-rc4"

projects[jquery_update][version] = "2.3"

projects[features][version] = "2.0-beta2"

; Themes
projects[bootstrap][version] = "2.0-beta3"

; Libraries
;libraries[leaflet][download][type] = get
;libraries[leaflet][download][url] = http://twitter.github.io/bootstrap/assets/bootstrap.zip
;libraries[leaflet][directory_name] = 
